apiVersion: v1
kind: Secret
metadata:
  name: storage-secret
type: Opaque
stringData:
  azurestorageaccountname: cG9zdGdyZXNjcm9uam9i
  azurestorageaccountkey: dVBuQkkyMzkyMm1xUW1ZbytMQ0xMdnJIeFR2MUxJTmhuYlAzZ2NycEZHcUpLZHBGdXdUQnFxbU9INFA5bzhNako5bHJSTkhkbE1WUU9kM0RXdTBjb2c9PQ==
